# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrt < Formula
  desc "A secret manager for the command-line"
  homepage "https://github.com/loderunner/scrt"
  version "0.0.6"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/loderunner/scrt/releases/download/v0.0.6/scrt_0.0.6_darwin_x86_64.tar.gz"
    sha256 "97fd0053c995fe9247bd55637acb5f62c803b893fb7f2d6d54eb82e0dfee618b"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/loderunner/scrt/releases/download/v0.0.6/scrt_0.0.6_darwin_arm64.tar.gz"
    sha256 "a9c68addcda877c1a8398edfeb3990fa427662c4a051c773e469cec00b3eb367"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/loderunner/scrt/releases/download/v0.0.6/scrt_0.0.6_linux_x86_64.tar.gz"
    sha256 "ba3b2b9a88537b48332c3fe2fed809219a726809b6be77d83b3b31537ca0d95d"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/loderunner/scrt/releases/download/v0.0.6/scrt_0.0.6_linux_armv6.tar.gz"
    sha256 "2af7e58d6e75ef3dc800362aa9d7d69f5538e8053f4b9d30d1ef72fa63f6e8c4"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/loderunner/scrt/releases/download/v0.0.6/scrt_0.0.6_linux_arm64.tar.gz"
    sha256 "84bfbe177fe23d8107c36c1dda3abce6504d1bc2778f4ca6aef295463f4d3846"
  end

  def install
    bin.install "scrt"
  end

  test do
    system "#{bin}/scrt --version"
  end
end
